
name: My First CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Linux environment
        run: |
          pwd
          ls

      - name: Check Python
        run: python --version

      - name: Run test
        run: echo "My CI pipeline works!"
